[package]
name = "JA2-ConvertXMLData"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.26.0" }

[profile.release]
opt-level = 3
lto = true
strip = true  # Automatically strip symbols from the binary.
